### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by Aylin67** [SistemasTecTlaxiaco/infografia-de-las-librerias-Aylin67#2]
[Infografia Informativa Bellas Artes Cuadros Simple Llamativa Azul.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-Aylin67/files/15043992/Infografia.Informativa.Bellas.Artes.Cuadros.Simple.Llamativa.Azul.pdf)

**Comment by AricelCastro** [comment]
nuestro equipo le da una calificacion de 18/20 falto mas ventajas y desventajas

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
